# Generated by Django 2.2b1 on 2019-02-18 17:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序值')),
                ('star_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='主题数')),
                ('brief', models.CharField(blank=True, max_length=512, null=True, verbose_name='简介')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wepost_posts.Node', verbose_name='父节点')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
