# Generated by Django 2.2b1 on 2019-02-18 17:22

from django.db import migrations

from wepost.apps.posts.models import Node


def init_nodes(apps, schema_editor):
    p = Node(code="programming",name="编程")
    p.save()
    assert p.pk


    lisp = Node(code="lisp",parent=p)
    haskell = Node(code="haskell",parent=p)
    c = Node(code="c",parent=p)
    cpp = Node(code="c++",parent=p)
    go = Node(code="go",parent=p)
    rust = Node(code="rust",parent=p)
    java = Node(code="java",parent=p)
    kotlin = Node(code="kotlin",parent=p)
    scala = Node(code="scala",parent=p)
    swift = Node(code="swift",parent=p)
    objc = Node(code="objc",name="Objective-C",parent=p)
    py = Node(code="python",parent=p)
    perl = Node(code="perl",parent=p)
    php = Node(code="php",name="PHP",parent=p)
    ruby = Node(code="ruby",parent=p)
    lua = Node(code="lua",parent=p)
    css = Node(code="css",name="CSS",parent=p)
    html = Node(code="html",name="HTML",parent=p)
    js = Node(code="javascript",parent=p)
    for node in [lisp,haskell, c,cpp,go,rust,java,kotlin,scala,swift,objc,py,perl,php,ruby,lua,js,css,html]:
        node.save()
    assert py.pk
    py_nodes = [
        Node(code="django",parent=py),
        Node(code="flask",parent=py),
        Node(code="sqlalchemy",name="SQLAlchemy",parent=py),
        Node(code="pytest",parent=py),
        Node(code="celery",parent=py),
        Node(code="jinja",parent=py),
        Node(code="jupyter",parent=py),
        Node(code="sentry",parent=py),
        Node(code="scikit-learn",name="scikit-learn",parent=py),
    ]
    assert js.pk
    js_nodes = [
        Node(code="typescript", name="TypeScript", parent=js),
        Node(code="nodejs", name="Node.js", parent=js),
        Node(code="vue", name="Vue.js", parent=js),
        Node(code="webpack",  parent=js),
        Node(code="react",  parent=js),
    ]
    for node in ( py_nodes + js_nodes ):
        node.save()

    db = Node(code="database",name="数据库")
    db.save()
    mysql = Node(code="mysql", name="MySQL",parent=db)
    psql = Node(code="postgresql", name="PostgreSQL",parent=db)
    redis = Node(code="redis", parent=db)
    mongo = Node(code="mongodb", name="MongoDB", parent=db)
    sqlite = Node(code="sqlite", name="SQLite", parent=db)

    for node in ([mysql, psql, redis, mongo, sqlite]):
        node.save()

    cloud = Node(code="cloud", name="云计算")
    cloud.save()
    docker = Node(code="docker", parent=cloud)
    nginx = Node(code="nginx", parent=cloud)
    for node in [docker, nginx]:
        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wepost_posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_nodes)
    ]
