# Generated by Django 2.2b1 on 2019-02-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid
import wepost.apps.posts.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wepost_posts', '0002_init_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='喜欢数')),
                ('dislike_count', models.PositiveIntegerField(default=0, verbose_name='不喜欢数')),
                ('fav_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享数')),
                ('_deleted_at', models.DateTimeField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(max_length=40960, verbose_name='内容')),
                ('content_rendered', models.TextField(default='', max_length=81920, verbose_name='渲染内容')),
                ('state', models.SmallIntegerField(choices=[(1, '草稿'), (6, '已发布')], default=wepost.apps.posts.enums.PostState(1), verbose_name='状态')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('last_reply_by', models.CharField(blank=True, default='', max_length=150, verbose_name='最后回复人')),
                ('last_touched', models.DateTimeField(auto_now=True, verbose_name='最后活跃')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='回复数')),
                ('member_view_count', models.PositiveIntegerField(default=0, verbose_name='会员浏览数')),
                ('other_view_count', models.PositiveIntegerField(default=0, verbose_name='网页浏览数')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
            },
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '节点', 'verbose_name_plural': '节点'},
        ),
        migrations.AlterField(
            model_name='node',
            name='star_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='喜欢数')),
                ('dislike_count', models.PositiveIntegerField(default=0, verbose_name='不喜欢数')),
                ('fav_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享数')),
                ('_deleted_at', models.DateTimeField(null=True)),
                ('content', models.TextField(max_length=4096, verbose_name='内容')),
                ('content_rendered', models.TextField(default='', max_length=8192, verbose_name='渲染内容')),
                ('creator_name', models.CharField(max_length=150, verbose_name='回复人名')),
                ('reply_from', models.CharField(help_text='用户来源地点等信息', max_length=64, verbose_name='回复人来源')),
                ('reply_ip', models.GenericIPAddressField(verbose_name='回复IP')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepost_posts.Post', verbose_name='主题')),
                ('ref', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='wepost_posts.Reply', verbose_name='引用')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wepost_posts.Node', verbose_name='节点'),
        ),
        migrations.CreateModel(
            name='UserNodeStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.IntegerField(default=0, help_text='用于排序关注显示顺序', verbose_name='排序')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, '关注'), (4, '屏蔽')], default=wepost.apps.posts.enums.UserNodeStarState(1), verbose_name='状态')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wepost_posts.Node', verbose_name='节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注节点',
                'verbose_name_plural': '关注节点',
                'unique_together': {('user', 'node')},
            },
        ),
    ]
