# Generated by Django 2.2b1 on 2019-02-23 10:43

from django.db import migrations

from wepost.apps.auth.models import WepostUser
from wepost.apps.posts.models import Node
from wepost.apps.posts.services import UserNodeService


def dev_user_start_some_nodes(app,se):
  import random
  nodes = list(Node.objects.all())
  names = [f"dev{i}" for i in range(10)]
  for name in names:
    user = WepostUser.objects.get(username=name)
    service = UserNodeService(user)
    k = int(len(nodes) * 0.3)
    some_nodes = random.choices(nodes, k=k)
    for node in some_nodes:
      service.star_node(node)

class Migration(migrations.Migration):

    dependencies = [
        ('wepost_posts', '0003_auto_20190221_1604'),
    ]

    operations = [
        migrations.RunPython(dev_user_start_some_nodes)
    ]
