# Generated by Django 2.2b1 on 2019-02-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, '关注'), (4, '屏蔽')], verbose_name='状态')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idol', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '关注与屏蔽',
                'verbose_name_plural': '关注与屏蔽',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
