# Generated by Django 2.2b1 on 2019-02-27 21:16

from django.db import migrations

from wepost.apps.auth.models import WepostUser
from wepost.apps.sns.services import UserRelationService


def dev_user_follow_block_some_users(apps,se):
    import random
    dev_users = list(WepostUser.objects.filter(username__istartswith="dev"))
    user_set = set(dev_users)
    for user in user_set:
        service = UserRelationService(user)
        other_users = set(user_set)
        other_users.remove(user)
        k = int(len(other_users) * 0.1)
        blocked_users = set(random.choices(list(other_users), k=k))
        for to in other_users:
            if to not in blocked_users:
              service.follow(to)
            else:
              service.block(to)





class Migration(migrations.Migration):

    dependencies = [
        ('wepost_sns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dev_user_follow_block_some_users)
    ]
