# Generated by Django 2.2b1 on 2019-02-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wepost.apps.wallets.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('_deleted_at', models.DateTimeField(null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='余额')),
                ('freeze', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='冻结')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'NEW'), (1, 'ACTIVE'), (4, 'STOP')], default=wepost.apps.wallets.enums.WalletState(1), verbose_name='状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '钱包',
                'verbose_name_plural': '钱包',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('_deleted_at', models.DateTimeField(null=True)),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, '收益'), (2, '支出')], verbose_name='收支方向')),
                ('category', models.PositiveSmallIntegerField(choices=[(101, '每日登录奖励'), (102, '每日活跃度奖励'), (110, '主题回复收益'), (111, '收到回复谢意'), (112, '收到主题谢意'), (201, '创建主题'), (202, '创建回复'), (211, '发送回复谢意'), (212, '发送主题谢意')], verbose_name='收支类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='数额')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='当前余额')),
                ('current_freeze', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='当前冻结')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='来源用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收支明细',
                'verbose_name_plural': '收支明细',
            },
        ),
    ]
