# Generated by Django 2.2b1 on 2019-02-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wepost.apps.notifications.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.BigIntegerField(choices=[(1, '收到回复'), (2, '收到@'), (4, '收到回复感谢'), (8, '收到主题感谢'), (16, '收到回复收藏'), (32, '收到主题收藏'), (64, '关注用户有了新回复'), (128, '关注用户创建了新主题'), (256, '关注的主题有了新回复'), (512, '关注的节点有了新主题')], verbose_name='类别')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '消息'), (1, '成功'), (2, '警告'), (3, '错误')], default=wepost.apps.notifications.enums.NotificationLevel(0), verbose_name='级别')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='未读')),
                ('actor_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, help_text='可以用来保存简短的回复等内容', null=True, verbose_name='备注')),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_target', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
